### ISSUE TITLE
Allow users to pass in params that get forwarded to request

### ISSUE THREAD

**Issue by jgrund** [jansepar/node-jenkins-api#22]
I am trying to connect to a Jenkins instance that uses a self-signed certificate. I like to be able to pass

```rejectUnauthorized : false``` to the underlying ```request``` instance. 

It would useful to allow the methods from this module to forward options to ```request```.

**Comment by chamerling** [comment]
Hi @jgrund,

Done in #27 

Cheers,

**Comment by jansepar** [comment]
@chamerling's change has been merged. Closing!
