### ISSUE TITLE
issue using https protocol

### ISSUE THREAD

**Issue by hridyeshpant** [jansepar/node-jenkins-api#25]
getting below error while using copy job API jenkins server is configured with HTTPS
SELF_SIGNED_CERT_IN_CHAIN.
Same things is working fine in other jenkins server which are in HTTP.

Can you please suggest,what is the issue with https?

**Comment by chamerling** [comment]
Hi @hridyeshpant,

done in #27 

Cheers

**Comment by jansepar** [comment]
PR has been +1ed and merged. Thanks again @chamerling!
