### ISSUE TITLE
Uncaught TypeError: self._qs.unescape is not a function

### ISSUE THREAD

**Issue by mnemanja** [jansepar/node-jenkins-api#56]
After requiring and initializing the library, the data fetch fails:
```
jenkins.all_jobs(function(err, data) {
   if (err){ return console.log(err); }
   console.log(data)
});
```
Error:
```
Uncaught TypeError: self._qs.unescape is not a function
```

Environment: Windows 10.
Node version: 6.5.0

**Comment by abaoaqus** [comment]
Hi @mnemanja, did you find the solution?

**Comment by mnemanja** [comment]
At the time I was testing the implementation and since I haven't given it any further effort. I'll close this issue since I will not be participating in it for the time being.

**Comment by veeral1995** [comment]
Anyone find a solution? I am having this same problem! After looking around the internet I still have yet to find a solution.

**Comment by veeral1995** [comment]
`import {Querystring} from "request/lib/querystring.js";
Querystring.prototype.unescape = function(val) {
    return val
};`

This is a pretty lazy/bad solution but it works. Just put this code in the file with the jenkinsapi code and it should solve the error!

**Comment by mjsornp** [comment]
> `import {Querystring} from "request/lib/querystring.js"; Querystring.prototype.unescape = function(val) { return val };`
> 
> This is a pretty lazy/bad solution but it works. Just put this code in the file with the jenkinsapi code and it should solve the error!

The solution works, tks a lot.
