### ISSUE TITLE
Can't have url special chars in password

### ISSUE THREAD

**Issue by msmagoo60** [jansepar/node-jenkins-api#59]
I came across this issue yesterday where we had to update the password of the user that we use to trigger the jenkins job. The new randomly generated password had a "/" in it and it completely broke everything. It appeared as though the "/" was confusing the request library and making it cut off at the slash and so the error I was getting was listing the user as the hostname and saying address not found. A co-worker suggested the use of the Node URI library which splits out the username and password and does encoding on them for you: https://nodejs.org/api/url.html#url_url_password.

**Comment by kub1x** [comment]
Hey, thanks for the catch. I've added an example to the docs. Cheers
