### ISSUE TITLE
Node 4 Compatibility Broken Since Refactor

### ISSUE THREAD

**Issue by chrisallmark** [jansepar/node-jenkins-api#61]
Compatibility with older versions of Node is broken. I'm running a ARMv6 Raspberry Pi based build monitor which is restricted to Node 4.7.1 and as of the 'complete refactoring' commit d654756d594d77657c94aa6bf32962dcfda10a2a is broken with the following error:

.../dist/node_modules/jenkins-api/lib/main.js:71
      [body, property, callback] = doArgs(arguments, ['string', 'string|array|function', 'function']);
      ^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
 
This hits as soon as var jenkinsapi = require("jenkins-api"); is called.

**Comment by kub1x** [comment]
Hey, you've probably installed directly from github. The version 0.2.8 on NPM is compatible with node 4. I'll try to make current code compatible with node 4 again using babel.

**Comment by chrisallmark** [comment]
I'm currently directly pulling commit 4cd954cef6cd70c659c72553d945872a3b5a5f81 ('huangrurong-huangrurong-patch-1') as a work around and everything's cool ... except that our builds are broken ;)

Keep up the good work...

**Comment by kub1x** [comment]
Hey, I've just pushed babel compiled version, could you try master now?

**Comment by chrisallmark** [comment]
All good. My headless build monitor is back up and running. Thanks!

![gif image-b0e7ab313af8-1](https://user-images.githubusercontent.com/6512790/28661345-41b32e78-72ae-11e7-83d1-14170afdb322.gif)

**Comment by kub1x** [comment]
Now this actually feels really good. And looks cool. If you have the source code somewhere just add a link to your comment ;) I'd like to take a glance.

**Comment by chrisallmark** [comment]
Sure. Can't vouch for the quality of my code though... ;)
https://github.com/giffgaff/jenkins-build-monitor-piglow

Basically it uses a PiGlow to display the overall status - red for a broken build, yellow/orange for a build in progress, green for all good and blue if Jenkins is down. I've just ordered a Pi Zero W with a Blinkt so I'll be doing a smaller version soon. We either use them on developers desks or pair them up with a monitor and use Chromium to display a styled version of the Jenkins Build Monitor Plugin (see https://github.com/jan-molak/jenkins-build-monitor-plugin) - here's my teams current status:

![img_8029](https://user-images.githubusercontent.com/6512790/28672110-b3d21b5e-72d6-11e7-96d9-4f5851ee8427.JPG)
