### ISSUE TITLE
some functions are missing/not available

### ISSUE THREAD

**Issue by andreash92** [jansepar/node-jenkins-api#62]
i am getting this error: 

> TypeError: jenkins.all_builds is not a function

so i decided to print the jenkins object like this 

`var jenkinsapi = require('jenkins-api');`
`var jenkins = jenkinsapi.init('https://${username}:${token}@my-jenkins-uri');`
`console.log(jenkins)`

and from the follow output it seems that some functions are missing for some reason... 
> { build: [Function: build],
  stop_build: [Function: stop_build],
  all_jobs: [Function: all_jobs],
  all_jobs_in_view: [Function: all_jobs_in_view],
  job_info: [Function: job_info],
  last_build_info: [Function: last_build_info],
  last_completed_build_info: [Function: last_completed_build_info],
  build_info: [Function: build_info],
  last_build_report: [Function: last_build_report],
  get_config_xml: [Function: get_config_xml],
  create_job: [Function: create_job],
  update_job: [Function: update_job],
  copy_job: [Function: copy_job],
  delete_job: [Function: delete_job],
  disable_job: [Function: disable_job],
  enable_job: [Function: enable_job],
  last_success: [Function: last_success],
  last_result: [Function: last_result],
  queue: [Function: queue],
  computers: [Function: computers],
  job_output: [Function: job_output] }

I am using node v6.11.1.
Any ideas?

**Comment by andreash92** [comment]
i compared the local file **main.js** in _node_modules/jenkins-api/lib/_ folder with the one in the github repo and they are different. I copied and pasted the file from github repo and now it seems to be working BUT every time i install the jenkins-api with the command `npm install jenkins-api` the file goes back to previous state and it doesn't work. Also, in the package.json it seems that i have the latest version of jenkins-api: `    "jenkins-api": "^0.2.8"`

i would like to hear and know why does this happens. 
Thanks

**Comment by chrisallmark** [comment]
The npm version is ways out of date I think. I installed directly from the repo:

  "dependencies": {
    "jenkins-api": "github:jansepar/node-jenkins-api",
  }

**Comment by andreash92** [comment]
thanks 
although i don't understand why npm is not automatically updated from GitHub repo, it seems installing directly from github repo is the way to go

**Comment by kub1x** [comment]
@andreash92 Hay, thanks for the note. NPM holds what the original devs deployed as a stable version two years ago and I'm trying to do quite some upgrade (there were 13 PRs waiting) and testing before I publish the next version. Please be patient.

**Comment by andreash92** [comment]
makes sense now, thanks for letting us know! keep up the good work

**Comment by kub1x** [comment]
@andreash92, @chrisallmark the version 0.3.1 is out now ;)
