### ISSUE TITLE
Server returned unexpected status code: 403

### ISSUE THREAD

**Issue by dylanyg** [jansepar/node-jenkins-api#66]
const JenkinsUrl= new URL("http://uname@ip:8080")
JenkinsUrl.password="*******";
console.log(JenkinsUrl.href);
var jenkins=jenkinsapi.init(JenkinsUrl.href);
jenkins.build('test1', {token: '1234'}, function(err, data) {
  if (err){ return console.log(err); }
  console.log(data)
});

**Comment by vaimr** [comment]
May be CSRF Protection enabled

**Comment by ddimitrioglo** [comment]
Confirm this issue.
@vaimr Can we workaround it somehow?

**Comment by dylanyg** [comment]
thank you every much!!
the problem has been solved.
note:jenkins-Setting-Configure Global Security-CSRF Protection

**Comment by vaimr** [comment]
@ddimitrioglo https://github.com/jansepar/node-jenkins-api/issues/58

**Comment by ddimitrioglo** [comment]
@dylanyg Could you please provide an example here?
